Resources:
  DynamoDBTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        -
          AttributeName: pk
          AttributeType: S
      KeySchema:
        -
          AttributeName: pk
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      

Outputs:
  DynamoDBTableArn:
    Value:
      !GetAtt DynamoDBTable.Arn
    Export:
      Name: ${self:custom.resourcesStage}-DynamoDBTableArn

  DynamoDBTableRef:
    Value: !Ref DynamoDBTable
    Export:
      Name: ${self:custom.resourcesStage}-DynamoDBTableName